### ISSUE TITLE
Not work 

### ISSUE THREAD

**Issue by majovec** [Infernus101/Tesseract-Resurrected#6]
Not work build in 128+y  now work only old limit 
not work floatingtet particle

**Comment by Infernus101** [comment]
Please follow the issue format

**Comment by kenygamer** [comment]
@Infernus101 If you close this problem, then why do you update **FloatingTextParticle**? I think you should wait for @majovec to submit a new issue that meets the format, and then take action on the matter. I do not think that @majovec will create the issue again, because it is already solved.

What this comment wants, is that, in this way people learn to follow instructions.
